sqlALTER TABLE users ADD COLUMN IF NOT EXISTS gitlab_id text UNIQUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS gitlab_login text;
ALTER TABLE users ALTER COLUMN github_id DROP NOT NULL;
ALTER TABLE users ALTER COLUMN github_login DROP NOT NULL;
